# Generated by Django 4.1.2 on 2023-04-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipapp', '0002_imagemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(default='SOME_STRING', max_length=100),
        ),
    ]
