# Generated by Django 2.2.12 on 2023-05-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipapp', '0003_alter_imagemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
