# Generated by Django 2.2.12 on 2023-05-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipapp', '0004_auto_20230504_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='outputImg',
            field=models.ImageField(default='Some life', upload_to='images/output'),
        ),
    ]
