# Generated by Django 2.2.12 on 2023-05-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipapp', '0005_imagemodel_outputimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='outputImg',
            field=models.ImageField(upload_to='images/output'),
        ),
    ]
