# Generated by Django 4.2.1 on 2023-05-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipapp', '0006_auto_20230504_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
