# Generated by Django 4.1.7 on 2023-03-05 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageInput', '0002_image_delete_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='language',
        ),
        migrations.RemoveField(
            model_name='image',
            name='price',
        ),
    ]
